### ISSUE TITLE
Task #2: command line arguments

### ISSUE THREAD

**Issue by blixtra** [learning-playground/learning-go#8]
Now we want to make a version of Task 1 (issue #3) that does the same thing but accepts a command line argument to specify the file path.

For example,  we should be able to run run something like this...

```
parse-file-cli --input=./source
```

To do this, we'll need to use the [flag pkg](https://golang.org/pkg/flag/)

The could should be in `Playground/Task#2-Command-Line/parse-file-cli.go`

**Comment by IrenaBenja** [comment]
@blixtra you can take a look if there is something that needs to be changed
